### ISSUE TITLE
httpclient 4.1.1 and ntlm

### ISSUE THREAD

**Issue by buehlera** [SmartBear/soapui#10]
Dear Devs
We have been experimenting with soapUI for quite a while and like it pretty much.
There is a project where we are having trouble with ntlm webservices in a bit of a complexe scenario. The bug is fully described here https://issues.apache.org/jira/browse/HTTPCLIENT-1107 and is fixed as of httpclient version 4.2.x.

I'd like to kindly ask you to update the httpclient library to a more uptodate version.
With best regards, Alican

**Comment by AlexanderYeremeyev** [comment]
Next release will contain solution for httpclient. These modules are updated on modern version.
Current "next" branch already contains needed fix

**Comment by steleug** [comment]
Thanks, @AlexanderYeremeyev !

**Comment by IlyaAvdeev** [comment]
Thank you, guys, closing the issue.
