### ISSUE TITLE
Security Vulnerabilities in SOAP UI Version 5.4.0(com.fasterxml.jackson.core » jackson-core)

### ISSUE THREAD

**Issue by guptaviv** [SmartBear/soapui#450]
Hello Team,

I could see some security vulnerabilities in soap ui version 5.4.0 related to jackson-core libraries while running a twistlock scan on soap ui docker image. Following error of the twist lock for your reference:-

1) FasterXML jackson-databind 2.x before 2.9.7 might allow remote attackers to conduct server-side request forgery (SSRF) attacks by leveraging failure to block the axis2-jaxws class from polymorphic deserialization.

2) XMLscanner.java in Apache Xerces2 Java Parser before 2.12.0, as used in the Java Runtime Environment (JRE) in IBM Java 5.0 before 5.0 SR16-FP3, 6 before 6 SR14, 6.0.1 before 6.0.1 SR6, and 7 before 7 SR5 as well as Oracle Java SE 7u40 and earlier, Java SE 6u60 and earlier, Java SE 5.0u51 and earlier, JRockit R28.2.8 and earlier, JRockit R27.7.6 and earlier, Java SE Embedded 7u40 and earlier, and possibly other products allows remote attackers to cause a denial of service via vectors related to XML attribute names.

It seems that SOAP UI is referring to jackson - core lib version 2.3.0 whereas the latest version is 2.9.8(refer the maven central link)
https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core

kindly assist on this.

Regards,
Vivek

**Comment by IlyaAvdeev** [comment]
Thanks for the heads-up, @guptaviv. We will proceed this thru our typical workflow.

**Comment by guptaviv** [comment]
@ilyaavdeev thanks for the update!

**Comment by AlexanderYeremeyev** [comment]
@guptaviv 
Next release will contain solution for jackson jars. These modules are excluded from soapui.
Current "next" branch already contains needed fix.

**Comment by guptaviv** [comment]
@AlexanderYeremeyev - Thanks for the update!
