### ISSUE TITLE
Authentication header not sent

### ISSUE THREAD

**Issue by phillip-haydon** [SmartBear/soapui#451]
If a contract contains a security policy for Basic Authentication, and you add the credentials, it will send the header.

It seems if a contract omits the policy, despite adding the credentials, SoapUI will not send the header. 

This can be verified by creating a request for a service which doesn't contain auth, then add auth to the request and click 'Raw' tab, the header will not be present.

**Comment by IlyaAvdeev** [comment]
hey, @phillip-haydon 
did you try the option below?
![image](https://user-images.githubusercontent.com/7438227/54456214-ab742100-476e-11e9-8d5e-194331bbdcd1.png)

**Comment by ReadyAPIAgent** [comment]
Closing due to age and lack of response
