### ISSUE TITLE
Cross-Domain NTLM Authentication returns 401

### ISSUE THREAD

**Issue by lcam0045** [SmartBear/soapui#457]
This might be a specific issue and I will try to explain it as efficiently as possible.

We have a REST API service set up on IIS 10 on a Windows 2016 server registered in DOMAIN-1. The providers are set to use NTLM and Negotiate. If I set the Authorization in SOAPUI to use NTLM and the credentials of a domain user in DOMAIN-1, authentication works. However, if I use credentials of a user in DOMAIN-2, I get a 401.

The kicker is here: browsing to the endpoint using any browser works, as well as switching off Authorization from SOAPUI and configuring Burp Suite to act as a local proxy and NTLMv2 and DOMAIN-2 user credentials to connect to the endpoint. The problem seems specific to the NTLM auth method being used in SOAPUI, perhaps related to httpclient 4.1.1?

Finally, I have access to the server and examined event logs related to the success and failed logins. The failed logs have a substatus of "0xC000006A", possibly meaning "user name is correct but the password is wrong". It is for sure not a typo.

I also tried to examine the NTLM challenges and responses using wireshark but I cannot understand why only the DOMAIN-1 users are working using SOAPUI.

Pre-emptive auth is unchecked.

In my research I have seen some issues with httpclient 4.1.1 - could it be related to this?

Thanks.

**Comment by IlyaAvdeev** [comment]
Hello, @lcam0045 . SoapUI is a free open source project, SmartBear doesn't provide support service for it. We have proprietary product ReadyAPI (which is more feature rich and powerful version of SoapUI), it's fully supported. Your issue doesn't look like a source code issue so if you want to address it you need to use [ReadyAPI (SoapUI Pro)](https://smartbear.com/product/ready-api/soapui/overview/) or jump in the [community ](https://community.smartbear.com/) and raise this question there.

**Comment by lcam0045** [comment]
Thanks @IlyaAvdeev , and sorry for the waste of time.

**Comment by IlyaAvdeev** [comment]
No worries, I wish I could help you.

**Comment by antone-sb** [comment]
@lcam0045 If you problem is related to httpclient-4.1.1, there is a chance it will be fixed in the next release, as we have just updated httpclient to 4.5.5. The fix is also in "next" branch, so you can build it yourself and try.

**Comment by lcam0045** [comment]
Hi @antone-sb , I am not sure if it is related to httpclient-4.1.1, however I am curious. Will try and build it and try. Many thanks!

**Comment by lcam0045** [comment]
Hi @antone-sb , I have tried building the new 5.6.0 version. I am currently behind a corporate Zscalar proxy, however specified in a settings.xml file for maven to use http repos. Anyway, it is finally building, however it is hitting the following error: 

`[ERROR] Failed to execute goal on project soapui: Could not resolve dependencies for project com.smartbear.soapui:soapui:jar:5.6.0-SNAPSHOT: The following artifacts could not be resolved: com.smartbear.utils.analytics:analytics-core:jar:5.6.0-SNAPSHOT, com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.6.0-SNAPSHOT: Failure to find com.smartbear.utils.analytics:analytics-core:jar:5.6.0-SNAPSHOT in http://repo.maven.apache.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central2 has elapsed or updates are forced -> [Help 1]`

Browsing to "http://smartbearsoftware.com/repository/maven2/com/smartbear/soapui/soapui/", I cannot seem to find any mention of 5.6.0. Am I doing something wrong?

Many thanks for your support.
