### ISSUE TITLE
App does not render correctly when DPI != 1

### ISSUE THREAD

**Issue by Xaeroxe** [SmartBear/soapui#462]
On Windows 10 when the DPI is not equal to 1 this app doesn't render at the correct modified DPI. This represents an accessibility issue for the vision impaired.

![DPI](https://user-images.githubusercontent.com/6182002/55977716-b5dde980-5c4c-11e9-94f7-cab03529ee5e.png)

**Comment by Xaeroxe** [comment]
This appears to be an issue with the Swing GUI toolkit. JavaFX is DPI aware, so Java apps report they're DPI aware, disabling the automatic Windows scaling, but Swing is not DPI aware, so no scaling occurs. This is fixed in Java 9+, but Java 9+ isn't at a stable release yet.

**Comment by ReadyAPIAgent** [comment]
Current SoapUI is based on 12+ Java, I hope this works for you now
