### ISSUE TITLE
Unable to build branch release-5.5.0

### ISSUE THREAD

**Issue by MalcolmAnderson** [SmartBear/soapui#463]
Summary - The 5.5 release seems to be looking for 5.6.0-SNAPSHOT versions of artifacts

Attached are the the output of 3 run attempts for the 5.5 release branch, 
[release-5.5.0_branch_failed_build.txt](https://github.com/SmartBear/soapui/files/3113714/release-5.5.0_branch_failed_build.txt)
[release-5.5.0_branch_failed_build_with_dash_e.txt](https://github.com/SmartBear/soapui/files/3113715/release-5.5.0_branch_failed_build_with_dash_e.txt)
[release-5.5.0_branch_failed_build_with_dash_X.txt](https://github.com/SmartBear/soapui/files/3113716/release-5.5.0_branch_failed_build_with_dash_X.txt)

The result of "mvn clean install" is in 
release-5.5.0_branch_failed_build.txt 

The result of "mvn -e clean install" is in 
release-5.5.0_branch_failed_build_with_dash_e.txt

The result of "mvn -X clean install" is in 
release-5.5.0_branch_failed_build_with_dash_X.txt

Below is the error :

[ERROR] Failed to execute goal on project soapui: Could not resolve dependencies for project com.smartbear.soapui:soapui:jar:5.6.0-SNAPSHOT: The following artifacts could not be resolved: com.smartbear.utils.analytics:analytics-core:jar:5.6.0-SNAPSHOT, com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.6.0-SNAPSHOT: Failure to find com.smartbear.utils.analytics:analytics-core:jar:5.6.0-SNAPSHOT in http://www.soapui.org/repository/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of smartbear-sweden-repository has elapsed or updates are forced -> [Help 1]

**Comment by IlyaAvdeev** [comment]
release-5.5.0 branch doesn't have any refereces on 5.6.0-SNAPSHOT artifacts.
https://github.com/SmartBear/soapui/blob/release-5.5.0/soapui/pom.xml

**Comment by MalcolmAnderson** [comment]
I have done a clone on a machine that has never had soapUI on it, attached are my results.
The first step was to clone the repository
The second step was to check out the release-5.5.0 branch
the final step was to run mvn clean install 3 times


mvn clean install > mvn_clean_install.txt
mvn -e clean install > mvn_clean_install_dash_e.txt
mvn -X clean install > mvn_clean_install_dash_X.txt


If there's any basic mistake I'm making, I'm happy to discover it.  

Thank you.


![04 - output of first mvn clean install](https://user-images.githubusercontent.com/1200043/57005216-e00b3300-6b8a-11e9-9905-8c12fc50d044.PNG)
![05 - output of second mvn clean install](https://user-images.githubusercontent.com/1200043/57005217-e00b3300-6b8a-11e9-9373-9e003cff43c0.PNG)
![06 - output of third mvn clean install](https://user-images.githubusercontent.com/1200043/57005218-e00b3300-6b8a-11e9-9876-4a248cdc8dd4.PNG)



![01 - Select Clone](https://user-images.githubusercontent.com/1200043/57005092-b43b7d80-6b89-11e9-9eb0-bce9e4c32243.PNG)

![02 - run clone command](https://user-images.githubusercontent.com/1200043/57005099-c5848a00-6b89-11e9-95d7-1be192a30ad9.PNG)

![03 - checkout release-5 5 0](https://user-images.githubusercontent.com/1200043/57005112-d503d300-6b89-11e9-9b1d-e6242472e216.PNG)

[mvn_clean_install_dash_X.txt](https://github.com/SmartBear/soapui/files/3133773/mvn_clean_install_dash_X.txt)
[mvn_clean_install.txt](https://github.com/SmartBear/soapui/files/3133774/mvn_clean_install.txt)
[mvn_clean_install_dash_e.txt]
(https://github.com/SmartBear/soapui/files/3133775/mvn_clean_install_dash_e.txt)

**Comment by JBarnesMCOS** [comment]
I have the same error; Clean build (brand new machine) 

Same steps as above (what is documented to get going)

Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.smartbear.utils.analytics:analytics-core:jar:5.6.0-SNAPSHOT in http://www.soapui.org/repository/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of smartbear-sweden-repository has elapsed or updates are forced

**Comment by IlyaAvdeev** [comment]
@JBarnesMCOS jump on release-5.5.0 branch, you're in "next"

**Comment by MalcolmAnderson** [comment]
@IlyaAvdeev I am not able to build on a clone of the release-5.5.0 branch, what steps should i take to either build it, or get you new information to troubleshoot it?

**Comment by chatelao** [comment]
I have tried to fix all broken dependencies:
- https://github.com/chatelao/soapui/tree/release-5.5.0

No idea if it will really build and no idea how the v5.5.0 was built.

**Comment by ReadyAPIAgent** [comment]
I guess you will not have any issues with 5.7.0 & 5.7.1-SNAPSHOT
