### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by avengerofpi** [SmartBear/soapui#469]
The project is ostensibly setup to compile and publish Java Docs, but there is very little actual documentation written. Most of the Java Doc output is just from the source code objects themselves (packages, classes, interfaces, methods, fields, etc?). We should work on adding human readable documentation to help users of the API.

c.f. "current" (v5.5.0 at time I am writing this) published Java Docs API - https://www.soapui.org/apidocs/overview-summary.html
(are there a stable links to the apidocs for release version?)

**Comment by IlyaAvdeev** [comment]
Hi, @avengerofpi, we will be happy to merge any contribution into our source code base (whether it's a code snippet or improved Java docs).

No there is no link on Java docs from prevous versions. I'll log correspondent ticket in our bug tracker. 

Thank you for your interest!

**Comment by avengerofpi** [comment]
Hi @IlyaAvdeev. One of my hopes by bringing this up (and hopefully contributing to this item) is to attract SmartBear's explicit interest in contributing to documenting their own API. This includes not only the FOSS version here that I am hoping to contribute to, but also the pro version API, which seems to be equally lacking real content and which only SmartBear itself is in a position to improve. I know SmartBear is really excited to keep getting out new and great features, but there would be so much value in creating mature API documentation that I'm sure both SmartBear and SmartBear's user base would benefit from flushing it out.

**Comment by IlyaAvdeev** [comment]
@avengerofpi  thank you for your feedback, we definitely do not pay much attention to Java docs on SoapUI OS side, but we are trying to improve it on ReadyAPI side, but you're right it's not an extensive activity though. I'll share your comment with our POs
