### ISSUE TITLE
Can't build SoapUI 5.5.0 or 5.4

### ISSUE THREAD

**Issue by pinpan** [SmartBear/soapui#475]
Hello,

Trying to build latest SoapUI . First tried master branch, then upon recommendation from another issue here on GH tried v 5.4 with same result.  The error message is :

```
[ERROR] Failed to execute goal on project soapui: Could not resolve dependencies for project com.smartbear.soapui:soapui:jar:5.6.0-SNAPSHOT: The following artifacts could not be resolved: com.smartbear.utils.analytics:analytics-core:jar:5.6.0-SNAPSHOT, com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.6.0-SNAPSHOT: Could not find artifact com.smartbear.utils.analytics:analytics-core:jar:5.6.0-SNAPSHOT in smartbear-sweden-repository (http://www.soapui.org/repository/maven2) -> [Help 1]
```

Tried in web browser the repository link: 
```
http://www.soapui.org/repository/maven2
```

Redirects to: 
```
https://rapi.tools.ops.smartbear.io/nexus/content/groups/public/maven2
```

Tried recommendation from: #463, so added  following repository to pom.xml:
```
<repository>
        <id>smartbearsoftware-repository</id>
        <url>http://smartbearsoftware.com/repository/maven2</url>
</repository>
```

Redirects to the same end point:  
```
https://rapi.tools.ops.smartbear.io/nexus/content/groups/public/maven2
```

Browsed a level up, no maven2 in 
```
https://rapi.tools.ops.smartbear.io/nexus/content/groups/public
```

My system although maybe irrelevant in this case is:
```
 Windows 10,
java version "1.8.0_221"
Apache Maven 3.6.1
git version 2.21.0.windows.1
```

Any suggestions welcome!

Pavlin

**Comment by IlyaAvdeev** [comment]
Hi, @pinpan, sorry for inconvinience, I'll jump on it ASAP.

**Comment by IlyaAvdeev** [comment]
Hi, @pinpan, please try this out again. Now it must work.

**Comment by initdch** [comment]
And it is gone again. How about hosting it on maven central?

**Comment by IlyaAvdeev** [comment]
This doesn't match our goals and priorities.
