### ISSUE TITLE
can i use soapui without the desktop app?

### ISSUE THREAD

**Issue by teaglebuilt** [SmartBear/soapui#506]
Can i use soapui's test runner in combination with groovy?

**Comment by ReadyAPIAgent** [comment]
Hi, @teaglebuilt, can you please describe your use case in details?

**Comment by teaglebuilt** [comment]
i would like to write test cases with a scripting language that soapui could interpret the same as using the desktop app. Using code with soapui's test runner, is this a thing?

**Comment by olensmar** [comment]
Hi @teaglebuilt - perhaps https://github.com/SmartBear/readyapi4j#getting-started-with-groovy is of interest? It's a groovy dsl for writing tests as code - using SoapUI as the underlying engine!?

**Comment by teaglebuilt** [comment]
@olensmar yes this is exactly what i was thinking about. thankyou

**Comment by olensmar** [comment]
Great! Let me know if you bump into any issues!
