### ISSUE TITLE
My eyes hurt by white

### ISSUE THREAD

**Issue by xoxloviwan** [SmartBear/soapui#512]
How to set dark theme to SoapUI ?

**Comment by xikandar** [comment]
6

**Comment by ReadyAPIAgent** [comment]
We didn't implement dark theme on SoapUI, but this was just recently released for ReadyAPI product.

**Comment by warrenc5** [comment]
My eyes are bleeding too from the screen shine.

Doesn't Java swing support plugable look and feel? 

https://github.com/weisJ/darklaf

**Comment by baptx** [comment]
> We didn't implement dark theme on SoapUI, but this was just recently released for ReadyAPI product.

It was not a reason to close this issue but at least someone made a pull request here:
https://github.com/SmartBear/soapui/pull/840

I tried another solution https://wiki.manjaro.org/index.php/Set_all_Java_apps_to_use_GTK%2B_font_%26_theme_settings but it made the app unusable even when enabling the "native Look & Feel" from SoapUI preferences.
