### ISSUE TITLE
soapui-maven-plugin requires Java 9

### ISSUE THREAD

**Issue by mprins** [SmartBear/soapui#528]
Not sure if intentional or not as I wan't able to find anything about this in the release notes, the soapui-maven-plugin now requires Java 9 as the classfile version is 53.0 so I'm seeing `java.lang.UnsupportedClassVersionError` errors on build server running with java 8
there is a note about "move to openjdk 12" but 53.0 (java 9) != 56.0 (java 12) and that would prevent using the plugin with any LTS java version.... please release a java 8 compatible version of the plugin.

see eg. https://github.com/B3Partners/kadaster-gds2/pull/65#pullrequestreview-447068119

**Comment by vincenzofiore** [comment]
I'm noticing the same issue. I need to use it with java 8. Please solve the issue.
