### ISSUE TITLE
Bundled JRE needs to be updated due to TLSv1.3 issues

### ISSUE THREAD

**Issue by joerg1985** [SmartBear/soapui#531]
The currently shipped JRE 12.0.1 has bugs related to TLSv1.3 connections, e.g. [JDK-8221253](https://bugs.openjdk.java.net/browse/JDK-8221253). 
This makes it impossible to work with TLSv1.3 only servers, the bundled JRE should be updated.

JRE 12 is out of support now, it might be better switching to a LTS version like 11.

**Comment by ReadyAPIAgent** [comment]
java16 is coming in 5.7.0
