### ISSUE TITLE
[Feature request] - add intellisense to Groovy editor

### ISSUE THREAD

**Issue by ouryperd** [SmartBear/soapui#535]
This is a feature request for intellisense / autocompletion in the Groovy editor to be added with https://github.com/bobbylight/RSyntaxTextArea
SoapUI Open Source is very powerful and can be better with this featuere. I answer a lot of SO questions about SoapUI and a lot of them would not be asked if code completion with a bit of reflexion worked.

Compare http://soapuirecipes.blogspot.com/2016/01/soapui-intellisense-groovy-code.html for reference.

I understand that this is an added feature in the paid-for version, but that version has many other premium features.

**Comment by ReadyAPIAgent** [comment]
please put you feature request in the community. This decision is out of dev power unfortunately.
