### ISSUE TITLE
SOAP Mock Response Start Step disappears

### ISSUE THREAD

**Issue by jpraet** [SmartBear/soapui#552]
See https://community.smartbear.com/t5/SoapUI-Open-Source/SOAP-Mock-Response-Start-Step-disappearing/m-p/186656

When you rename an assertion in a step that is referenced as a Start Step for a SOAP Mock Response, that start step reference also gets renamed to the new assertion name. This causes the start step to disappear when you reload the project.

I think the problem is here: https://github.com/SmartBear/soapui/blob/next/soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/WsdlMockResponseTestStep.java#L768

This code seems intended to update the start step when the referenced step gets renamed, but it also triggers when an assertion in the start step gets renamed.

**Comment by antone-sb** [comment]
Fixed in 5.7.0.
