### ISSUE TITLE
Build fails - The following artifacts could not be resolved: com.smartbear.utils.analytics:analytics-core:jar:5.5.4-SNAPSHOT, com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.5.4-SNAPSHOT

### ISSUE THREAD

**Issue by chatelao** [SmartBear/soapui#714]
[ERROR] Failed to execute goal on project soapui: Could not resolve dependencies for project com.smartbear.soapui:soapui:jar:5.7.1-SNAPSHOT: The following artifacts could not be resolved: com.smartbear.utils.analytics:analytics-core:jar:5.5.4-SNAPSHOT, com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.5.4-SNAPSHOT: Could not find artifact com.smartbear.utils.analytics:analytics-core:jar:5.5.4-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]

**Comment by johninaustin** [comment]
Same issue. 

POM FOR:
 - com.smartbear.utils.analytics:analytics-core:jar:5.5.4-SNAPSHOT is missing
 - com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.5.4-SNAPSHOT is missing

**Comment by ReadyAPIAgent** [comment]
fixed, please pull the latest changes.
